### ISSUE TITLE
support for unix socket

### ISSUE THREAD

**Issue by trinity-1686a** [sticnarf/tokio-socks#19]
For a personal project I need to connect to a local socks proxy through unix domain socket.
This is currently not supported by this crate, so I wanted to inquire if you were interested in supporting that, or if I should look for an other crate.
It could be done by allowing the end user to provide an AsyncRead+AsyncWrite, which would allow for [this](https://github.com/sticnarf/tokio-socks/issues/5#issuecomment-488779238) proposal to be implemented at the same time.

**Comment by sticnarf** [comment]
> It could be done by allowing the end user to provide an AsyncRead+AsyncWrite, which would allow for this proposal to be implemented at the same time.

Sounds like a good idea. I can add this feature but maybe not very soon.

Of couse, it'll be great if you can just open a pull request for it.

**Comment by trinity-1686a** [comment]
fixed by #20
