### ISSUE TITLE
Support futures ecosystem (that is: better support for non-tokio runtimes)

### ISSUE THREAD

**Issue by Congyuwang** [sticnarf/tokio-socks#42]
Currently the library feels too tightly coupled with tokio. Is it possible to refactor it to allow other runtimes that are compatible with the `futures` crate (such as `smol` or `async-std`)?

**Comment by Congyuwang** [comment]
Should I expect a new release on crate.io?

**Comment by sticnarf** [comment]
v0.5.2 has been released.

**Comment by Congyuwang** [comment]
Thanks a lot!
